kind: pipeline
type: docker
name: ci

steps:
  
- name: "Install angular-cli"
  image: node:10
  commands:
  - "npm install -g @angular/cli"
  
- name: "Install dependencies"
  image: node:10
  commands:
  - cd brainkeeper
  - npm install
  
- name: "Test"
  image: node:10
  commands:
  - cd brainkeeper
  - ng test
  
- name: "Lint"
  image: node:10
  commands:
  - cd brainkeeper
  - ng lint
