kind: pipeline
type: docker
name: ci

steps:

- name: "Install dependencies"
  image: node:10
  commands:
  - cd brainkeeper
  - npm install
  
- name: "Test"
  image: node:10
  commands:
  - cd brainkeeper
  - "npm run-script ng test --browsers ChromeHeadless --watch false"
  
- name: "Lint"
  image: node:10
  commands:
  - cd brainkeeper
  - npm run-script ng lint
