kind: pipeline
type: docker
name: ci

steps:

- name: "Install dependencies"
  image: node:10
  commands:
  - cd brainkeeper
  - npm install

- name: "Test & Coverage"
  image: buildkite/puppeteer
  commands:
  - cd brainkeeper
  - "npx ng test --browsers ChromeHeadlessNoSandbox --watch false --codeCoverage"

- name: "Upload to codecov"
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
  when:
    event:
    - push

- name: "Lint"
  image: node:10
  commands:
  - cd brainkeeper
  - "npx ng lint"
