kind: pipeline
type: docker
name: ci

steps:

- name: "Install dependencies"
  image: node:10
  commands:
  - cd brainkeeper
  - npm install

- name: "Test & Coverage"
  image: buildkite/puppeteer
  commands:
  - cd brainkeeper
  - "npx ng test --browsers ChromeHeadlessNoSandbox --watch false --codeCoverage"

- name: "Upload to codecov"
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token

- name: "Lint"
  image: node:10
  commands:
  - cd brainkeeper
  - "npx ng lint"

- name: "Build"
  image: node:10
  commands:
  - cd brainkeeper
  - npm run build
  when:
    event:
    - push

- name: "Docker tags"
  image: alpine
  commands:
  - echo -n "n-${DRONE_BUILD_NUMBER}," > .tags
  - if [ "${DRONE_BRANCH}" = "master" ]; then echo -n "latest" >> .tags; else echo -n "${DRONE_BRANCH}" >> .tags; fi;
  - echo -n "tags are "; cat .tags ; echo
  when:
    event:
    - push

- name: "Docker build & push"
  image: plugins/docker
  settings:
    repo: hmbrainkeeper/frontend
    username: hmbrainkeeper
    password:
      from_secret: hmbkdocker_password
    dockerfile: brainkeeper/Dockerfile
  when:
    event:
    - push
